.\" man page create by R# package system.
.TH PLANTMAT 2 2000-Jan "config" "config"
.SH NAME
config \- 
.SH SYNOPSIS
\fIconfig(\fBAglyconeType\fR as <integer> db_AglyconeType = [All], 
\fBAglyconeSource\fR as <integer> db_AglyconeSource = [All], 
\fBAglyconeMWRange\fR as any = [400,600], 
\fBNumofSugarAll\fR as any = [0,6], 
\fBNumofAcidAll\fR as any = [0,1], 
\fBNumofSugarHex\fR as any = [0,6], 
\fBNumofSugarHexA\fR as any = [0,6], 
\fBNumofSugardHex\fR as any = [0,6], 
\fBNumofSugarPen\fR as any = [0,6], 
\fBNumofAcidMal\fR as any = [0,1], 
\fBNumofAcidCou\fR as any = [0,1], 
\fBNumofAcidFer\fR as any = [0,1], 
\fBNumofAcidSin\fR as any = [0,1], 
\fBNumofAcidDDMP\fR as any = [0,1], 
\fBPrecursorIonType\fR as any = ["[M]+","[M]-","[M+H]+","[M-H]-"], 
\fBSearchPPM\fR as double = 10, 
\fBNoiseFilter\fR as double = 0.05, 
\fBmzPPM\fR as double = 30, 
\fBaglyconeSet\fR as list = \fB<NULL>\fR);\fR
.SH SEE ALSO
PlantMAT
.SH FILES
.PP
PlantMAT.dll
.PP
