.\" man page create by R# package system.
.TH PLANTMAT 2 2000-Jan "KNApSAcK.as.table" "KNApSAcK.as.table"
.SH NAME
KNApSAcK.as.table \- 
.SH SYNOPSIS
\fIKNApSAcK.as.table(\fBKNApSAcK\fR as any, 
\fBsolver\fR as <generic> GlycosylNameSolver = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
PlantMAT
.SH FILES
.PP
PlantMAT.dll
.PP
