.\" man page create by R# package system.
.TH PLANTMAT 2 2000-Jan "ms1.err" "ms1.err"
.SH NAME
ms1.err \- 
.SH SYNOPSIS
\fIms1.err(\fBmz\fR as double, 
\fBAglyW\fR as double, 
\fBAttn_w\fR as double, 
\fBnH2O_w\fR as double, 
\fBprecursor_type\fR as string = "[M+H]+");\fR
.SH SEE ALSO
PlantMAT
.SH FILES
.PP
PlantMAT.dll
.PP
