.\" man page create by R# package system.
.TH PLANTMAT 2 2000-Jan "MS1CP" "MS1CP"
.SH NAME
MS1CP \- 
.SH SYNOPSIS
\fIMS1CP(\fBquery\fR as <generic> Query[], 
\fBlibrary\fR as <generic> Library[], 
\fBsettings\fR as <generic> Settings, 
\fBionMode\fR as integer = 1, 
\fBsequenceMode\fR as boolean = FALSE, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
PlantMAT
.SH FILES
.PP
PlantMAT.dll
.PP
