.TH CONFIGDEFAULT 1 2022-09-15 "" "apply the default configuration"
.SH NAME
configDefault \- configDefault(
    <i>mzPPM</i> = 30,
    <i>precursors</i> = [[M]+, [M]-, [M+H]+, [M-H]-],
    <i>aglyconeSet</i> = <span style='color: blue;'>NULL</span>)
.SH SYNOPSIS
\fIconfigDefault(
    <i>mzPPM</i> = 30,
    <i>precursors</i> = [[M]+, [M]-, [M+H]+, [M-H]-],
    <i>aglyconeSet</i> = <span style='color: blue;'>NULL</span>)\fR
.SH OPTIONS
.PP
\fBmzPPM\fB \fR\- 30. ppm value for MS2 annotation
.PP
.PP
\fBprecursors\fB \fR\- [[M]+, [M]-, [M+H]+, [M-H]-]. 
.PP
.PP
\fBaglyconeSet\fB \fR\- NULL. a list of user defined aglycone candidate set.
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.configDefault at Run.R:line 27
.PP
.SH COPYRIGHT
Copyright © Feng Qiu (fengqiu1982 https://sourceforge.net/u/fengqiu1982/),  Licensed 2022
