.TH EXPORTJSON 1 2023-Sep "" "output the annotation result data set"
.SH NAME
exportJSON \- exportJSON(result,
    <i>file</i> = stdout)
.SH SYNOPSIS
\fIexportJSON(result,
    <i>file</i> = stdout)\fR
.SH OPTIONS
.PP
\fBresult\fB \fR\- . 
.PP
.PP
\fBfile\fB \fR\- stdout. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.exportJSON at Export.R:line 7
.PP
.SH COPYRIGHT
Copyright © Feng Qiu (fengqiu1982 https://sourceforge.net/u/fengqiu1982/),  Licensed 2023
