.\" man page create by R# package system.
.TH PLANTMAT 2 2000-Jan "as.query" "as.query"
.SH NAME
as.query \- create plantMAT query from the given mgf ion stream
.SH SYNOPSIS
\fIas.query(\fBmgf\fR as any, 
\fBmol_range\fR as any = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
create plantMAT query from the given mgf ion stream
.PP
.SH OPTIONS
.PP
\fBmgf\fB \fR\- the mgf ion collection or peak ms2 data model collection.. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
PlantMAT
.SH FILES
.PP
PlantMAT.Core.dll
.PP
.SH COPYRIGHT
Copyright © PlantMAT 2020
