.\" man page create by R# package system.
.TH PLANTMAT 2 2000-01-01 "fromKNApSAcK" "fromKNApSAcK"
.SH NAME
fromKNApSAcK \- Create PlantMAT reference meta library from KNApSAcK database
.SH SYNOPSIS
\fIfromKNApSAcK(\fBKNApSAcK\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Create PlantMAT reference meta library from KNApSAcK database
.PP
.SH OPTIONS
.PP
\fBKNApSAcK\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
PlantMAT
.SH FILES
.PP
PlantMAT.Core.dll
.PP
.SH COPYRIGHT
Copyright © PlantMAT 2020
