.\" man page create by R# package system.
.TH PLANTMAT 2 2000-Jan "MS1CP" "MS1CP"
.SH NAME
MS1CP \- Run ms1 search
.SH SYNOPSIS
\fIMS1CP(\fBquery\fR as <generic> Query[], 
\fBlibrary\fR as <generic> Library[], 
\fBsettings\fR as <generic> Settings, 
\fBionMode\fR as integer = 1, 
\fBsequenceMode\fR as boolean = FALSE, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Run ms1 search
.PP
.SH OPTIONS
.PP
\fBquery\fB \fR\- -. 
.PP
.PP
\fBlibrary\fB \fR\- -. 
.PP
.PP
\fBsettings\fB \fR\- -. 
.PP
.PP
\fBionMode\fB \fR\- -. 
.PP
.PP
\fBsequenceMode\fB \fR\- 
 run in algorithm debug mode, do not set this option to TRUE in production mode.
. 
.PP
.SH DETAILS
.PP
\fBoptions(verbose = TRUE)\fR for display debug information.
.PP
.SH SEE ALSO
PlantMAT
.SH FILES
.PP
PlantMAT.Core.dll
.PP
.SH COPYRIGHT
Copyright © PlantMAT 2020
