.\" man page create by R# package system.
.TH PLANTMAT 2 2000-Jan "MS1TopDown" "MS1TopDown"
.SH NAME
MS1TopDown \- performs combinatorial enumeration, and show the calculation progress (MS1CP)
.SH SYNOPSIS
\fIMS1TopDown(\fBlibrary\fR as <generic> Library[], 
\fBsettings\fR as <generic> Settings);\fR
.SH DESCRIPTION
.PP
performs combinatorial enumeration, and show the calculation progress (MS1CP)
.PP
.SH SEE ALSO
PlantMAT
.SH FILES
.PP
PlantMAT.Core.dll
.PP
.SH COPYRIGHT
Copyright © PlantMAT 2020
