.\" man page create by R# package system.
.TH PLANTMAT 2 2000-Jan "parseLibrary" "parseLibrary"
.SH NAME
parseLibrary \- read ms1 library file
.SH SYNOPSIS
\fIparseLibrary(\fBdata\fR as list);\fR
.SH DESCRIPTION
.PP
read ms1 library file
.PP
.SH SEE ALSO
PlantMAT
.SH FILES
.PP
PlantMAT.Core.dll
.PP
.SH COPYRIGHT
Copyright © PlantMAT 2020
