.\" man page create by R# package system.
.TH PLANTMAT 2 2000-Jan "precursor_types" "precursor_types"
.SH NAME
precursor_types \- 
.SH SYNOPSIS
\fIprecursor_types(\fBsettings\fR as <generic> Settings, 
\fBprecursor_types\fR as string);\fR
.SH SEE ALSO
PlantMAT
.SH FILES
.PP
PlantMAT.Core.dll
.PP
.SH COPYRIGHT
Copyright © PlantMAT 2020
