.\" man page create by R# package system.
.TH PLANTMAT 2 2000-Jan "report.table" "report.table"
.SH NAME
report.table \- run report table output
.SH SYNOPSIS
\fIreport.table(\fBresult\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
run report table output
.PP
.SH OPTIONS
.PP
\fBresult\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
PlantMAT
.SH FILES
.PP
PlantMAT.Core.dll
.PP
.SH COPYRIGHT
Copyright © PlantMAT 2020
