.\" man page create by R# package system.
.TH PLANTMAT 2 2020-08-04 "as.query" "as.query"
.SH NAME
as.query \- create plantMAT query from the given mgf ion stream
.SH SYNOPSIS
\fIas.query(\fBmgf\fR as <generic> Object, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
create plantMAT query from the given mgf ion stream
.PP
.SH OPTIONS
.PP
\fBmgf\fB \fR\- -
.PP
.PP
\fBenv\fB \fR\- -
.PP
.SH SEE ALSO
PlantMAT
.SH FILES
.PP
PlantMAT.Core.dll
.PP
.SH COPYRIGHT
Copyright © PlantMAT 2020
