.\" man page create by R# package system.
.TH PLANTMAT 2 2020-08-03 "config" "config"
.SH NAME
config \- create plantMAT configuration
.SH SYNOPSIS
\fIconfig(\fBExternalAglyconeDatabase\fR as string = \fB<NULL>\fR, 
\fBAglyconeType\fR as <integer> db_AglyconeType = [All], 
\fBAglyconeSource\fR as <integer> db_AglyconeSource = [All], 
\fBAglyconeMWRange\fR as <generic> Object = [400,600], 
\fBNumofSugarAll\fR as <generic> Object = [0,6], 
\fBNumofAcidAll\fR as <generic> Object = [0,1], 
\fBNumofSugarHex\fR as <generic> Object = [0,6], 
\fBNumofSugarHexA\fR as <generic> Object = [0,6], 
\fBNumofSugardHex\fR as <generic> Object = [0,6], 
\fBNumofSugarPen\fR as <generic> Object = [0,6], 
\fBNumofAcidMal\fR as <generic> Object = [0,1], 
\fBNumofAcidCou\fR as <generic> Object = [0,1], 
\fBNumofAcidFer\fR as <generic> Object = [0,1], 
\fBNumofAcidSin\fR as <generic> Object = [0,1], 
\fBNumofAcidDDMP\fR as <generic> Object = [0,1], 
\fBPrecursorIonType\fR as string = "[M-H]-", 
\fBPrecursorIonMZ\fR as double = -1.007277, 
\fBPrecursorIonN\fR as integer = 1, 
\fBSearchPPM\fR as double = 10, 
\fBNoiseFilter\fR as double = 0.05, 
\fBmzPPM\fR as double = 15, 
\fBPatternPrediction\fR as boolean = TRUE);\fR
.SH DESCRIPTION
.PP
create plantMAT configuration
.PP
.SH OPTIONS
.PP
\fBExternalAglyconeDatabase\fB \fR\- -
.PP
.PP
\fBAglyconeType\fB \fR\- -
.PP
.PP
\fBAglyconeSource\fB \fR\- -
.PP
.PP
\fBAglyconeMWRange\fB \fR\- -
.PP
.PP
\fBNumofSugarAll\fB \fR\- -
.PP
.PP
\fBNumofAcidAll\fB \fR\- -
.PP
.PP
\fBNumofSugarHex\fB \fR\- -
.PP
.PP
\fBNumofSugarHexA\fB \fR\- -
.PP
.PP
\fBNumofSugardHex\fB \fR\- -
.PP
.PP
\fBNumofSugarPen\fB \fR\- -
.PP
.PP
\fBNumofAcidMal\fB \fR\- -
.PP
.PP
\fBNumofAcidCou\fB \fR\- -
.PP
.PP
\fBNumofAcidFer\fB \fR\- -
.PP
.PP
\fBNumofAcidSin\fB \fR\- -
.PP
.PP
\fBNumofAcidDDMP\fB \fR\- -
.PP
.PP
\fBPrecursorIonType\fB \fR\- -
.PP
.PP
\fBPrecursorIonMZ\fB \fR\- -
.PP
.PP
\fBPrecursorIonN\fB \fR\- -
.PP
.PP
\fBSearchPPM\fB \fR\- -
.PP
.PP
\fBNoiseFilter\fB \fR\- -
.PP
.PP
\fBmzPPM\fB \fR\- -
.PP
.PP
\fBPatternPrediction\fB \fR\- -
.PP
.SH SEE ALSO
PlantMAT
.SH FILES
.PP
PlantMAT.Core.dll
.PP
.SH COPYRIGHT
Copyright © PlantMAT 2020
