.\" man page create by R# package system.
.TH PLANTMAT 2 2020-08-03 "join.ms2" "join.ms2"
.SH NAME
join.ms2 \- join ms2 spectra data with the corresponding ms1 query values
.SH SYNOPSIS
\fIjoin.ms2(\fBms1\fR as <generic> Object, 
\fBfiles\fR as string, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
join ms2 spectra data with the corresponding ms1 query values
.PP
.SH OPTIONS
.PP
\fBms1\fB \fR\- the ms1 peak features
.PP
.PP
\fBfiles\fB \fR\- a file path vector of the ms2 spectra matrix list for each ms1 peaks
.PP
.PP
\fBenv\fB \fR\- -
.PP
.SH SEE ALSO
PlantMAT
.SH FILES
.PP
PlantMAT.Core.dll
.PP
.SH COPYRIGHT
Copyright © PlantMAT 2020
