.\" man page create by R# package system.
.TH PLANTMAT 2 2020-08-03 "MS2ATopDown" "MS2ATopDown"
.SH NAME
MS2ATopDown \- performs MS2 annotation
.SH SYNOPSIS
\fIMS2ATopDown(\fBsettings\fR as <generic> Settings);\fR
.SH DESCRIPTION
.PP
performs MS2 annotation
.PP
.SH OPTIONS
.PP
\fBsettings\fB \fR\- -
.PP
.SH SEE ALSO
PlantMAT
.SH FILES
.PP
PlantMAT.Core.dll
.PP
.SH COPYRIGHT
Copyright © PlantMAT 2020
