.\" man page create by R# package system.
.TH PLANTMAT 2 2020-08-03 "parse.config" "parse.config"
.SH NAME
parse.config \- parse the settings value from a given json string
.SH SYNOPSIS
\fIparse.config(\fBjson\fR as string);\fR
.SH DESCRIPTION
.PP
parse the settings value from a given json string
.PP
.SH OPTIONS
.PP
\fBjson\fB \fR\- settings value in json text format.
.PP
.SH SEE ALSO
PlantMAT
.SH FILES
.PP
PlantMAT.Core.dll
.PP
.SH COPYRIGHT
Copyright © PlantMAT 2020
