.\" man page create by R# package system.
.TH PLANTMAT 2 2000-01-01 "config" "config"
.SH NAME
config \- create plantMAT configuration
.SH SYNOPSIS
\fIconfig(\fBAglyconeType\fR as <integer> db_AglyconeType = [All], 
\fBAglyconeSource\fR as <integer> db_AglyconeSource = [All], 
\fBAglyconeMWRange\fR as any = [400,600], 
\fBNumofSugarAll\fR as any = [0,6], 
\fBNumofAcidAll\fR as any = [0,1], 
\fBNumofSugarHex\fR as any = [0,6], 
\fBNumofSugarHexA\fR as any = [0,6], 
\fBNumofSugardHex\fR as any = [0,6], 
\fBNumofSugarPen\fR as any = [0,6], 
\fBNumofAcidMal\fR as any = [0,1], 
\fBNumofAcidCou\fR as any = [0,1], 
\fBNumofAcidFer\fR as any = [0,1], 
\fBNumofAcidSin\fR as any = [0,1], 
\fBNumofAcidDDMP\fR as any = [0,1], 
\fBPrecursorIonType\fR as any = ["[M]+","[M]-","[M+H]+","[M-H]-"], 
\fBSearchPPM\fR as double = 10, 
\fBNoiseFilter\fR as double = 0.05, 
\fBmzPPM\fR as double = 30, 
\fBaglyconeSet\fR as list = \fB<NULL>\fR);\fR
.SH DESCRIPTION
.PP
create plantMAT configuration
 
 if all of the parameter is omit, then you can create a settings 
 model with all configuration set to default values.
.PP
.SH OPTIONS
.PP
\fBAglyconeType\fB \fR\- -. 
.PP
.PP
\fBAglyconeSource\fB \fR\- -. 
.PP
.PP
\fBAglyconeMWRange\fB \fR\- -. 
.PP
.PP
\fBNumofSugarAll\fB \fR\- -. 
.PP
.PP
\fBNumofAcidAll\fB \fR\- -. 
.PP
.PP
\fBNumofSugarHex\fB \fR\- -. 
.PP
.PP
\fBNumofSugarHexA\fB \fR\- -. 
.PP
.PP
\fBNumofSugardHex\fB \fR\- -. 
.PP
.PP
\fBNumofSugarPen\fB \fR\- -. 
.PP
.PP
\fBNumofAcidMal\fB \fR\- -. 
.PP
.PP
\fBNumofAcidCou\fB \fR\- -. 
.PP
.PP
\fBNumofAcidFer\fB \fR\- -. 
.PP
.PP
\fBNumofAcidSin\fB \fR\- -. 
.PP
.PP
\fBNumofAcidDDMP\fB \fR\- -. 
.PP
.PP
\fBPrecursorIonType\fB \fR\- 
 a character vector of list all precursor types that could be apply 
 for search the ms1 annotation in plantMAT.
. 
.PP
.PP
\fBSearchPPM\fB \fR\- -. 
.PP
.PP
\fBNoiseFilter\fB \fR\- -. 
.PP
.PP
\fBmzPPM\fB \fR\- -. 
.PP
.SH SEE ALSO
PlantMAT
.SH FILES
.PP
PlantMAT.Core.dll
.PP
.SH COPYRIGHT
Copyright © PlantMAT 2020
