.\" man page create by R# package system.
.TH PLANTMAT 2 2000-01-01 "ms1.err" "ms1.err"
.SH NAME
ms1.err \- debug test tools
.SH SYNOPSIS
\fIms1.err(\fBmz\fR as double, 
\fBAglyW\fR as double, 
\fBAttn_w\fR as double, 
\fBnH2O_w\fR as double, 
\fBprecursor_type\fR as string = "[M+H]+");\fR
.SH DESCRIPTION
.PP
debug test tools
.PP
.SH OPTIONS
.PP
\fBmz\fB \fR\- ms1 \fBm/z\fR value. 
.PP
.PP
\fBAglyW\fB \fR\- exact mass. 
.PP
.PP
\fBAttn_w\fB \fR\- -. 
.PP
.PP
\fBnH2O_w\fB \fR\- -. 
.PP
.PP
\fBprecursor_type\fB \fR\- -. 
.PP
.SH SEE ALSO
PlantMAT
.SH FILES
.PP
PlantMAT.Core.dll
.PP
.SH COPYRIGHT
Copyright © PlantMAT 2020
