.TH EXPORTTABLE 1 2021-05-12 "" "export result as excel table"
.SH NAME
exportTable \- exportTable(result, file = stdout)
.SH SYNOPSIS
\fIexportTable(result, file = stdout)\fR
.SH OPTIONS
.PP
\fBresult\fB \fR\- 
.PP
.PP
\fBfile\fB \fR\- stdout
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.exportTable at Export.R:line 17
.PP
.SH COPYRIGHT
Copyright © Feng Qiu (fengqiu1982 https://sourceforge.net/u/fengqiu1982/),  Licensed 2021
