.TH KNAPSACKLIBRARY 1 2022-09-15 "" "KNApSAcKLibrary"
.SH NAME
KNApSAcKLibrary \- KNApSAcKLibrary(query,
    <i>cache</i> = ./)
.SH SYNOPSIS
\fIKNApSAcKLibrary(query,
    <i>cache</i> = ./)\fR
.SH OPTIONS
.PP
\fBquery\fB \fR\- . 
.PP
.PP
\fBcache\fB \fR\- ./. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.KNApSAcKLibrary at KNApSAcK.R:line 2
.PP
.SH COPYRIGHT
Copyright © Feng Qiu (fengqiu1982 https://sourceforge.net/u/fengqiu1982/),  Licensed 2022
