.TH KNAPSACKLIBRARY 1 2021-05-18 "" "KNApSAcKLibrary"
.SH NAME
KNApSAcKLibrary \- KNApSAcKLibrary(query, cache = ./)
.SH SYNOPSIS
\fIKNApSAcKLibrary(query, cache = ./)\fR
.SH OPTIONS
.PP
\fBquery\fB \fR\- 
.PP
.PP
\fBcache\fB \fR\- ./
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.KNApSAcKLibrary at KNApSAcK.R:line 2
.PP
.SH COPYRIGHT
Copyright © Feng Qiu (fengqiu1982 https://sourceforge.net/u/fengqiu1982/),  Licensed 2021
